name: Java CI with Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradle
      run: |
        chmod +x gradlew
        chmod +x gradle-5.0
    - name: Show the Gradle can work
      run: ./gradle-5.0/bin/gradle task
    - name: Compile with Gradle
      run: ./gradle-5.0/bin/gradle compileJava
    - name: Test GameTest.java 
      run: ./gradle-5.0/bin/gradle test
    - name: Assemble
      run: ./gradle-5.0/bin/gradle assemble
    - name: Show the path
      run: ls ./build/reports
    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: build/reports/tests/
    - name: Upload Assember Jav
      uses: actions/upload-artifact@v2
      with:
        name: Assember_Jarfile
        path: build
