name: Java CI with Gradle

on: [push]

jobs:
  Compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradle
      run: |
        chmod +x gradlew
        chmod +x gradle-5.0
    - name: Show the Gradle can work
      run: ./gradle-5.0/bin/gradle task
    - name: Compile with Gradle
      run: ./gradle-5.0/bin/gradle compileJava
  Test:
    needs: Compile
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradle
      run: |
        chmod +x gradlew
        chmod +x gradle-5.0
    - name: Test GameTest.java 
      run: ./gradle-5.0/bin/gradle test
    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: build/reports/tests/
  Assember:
    needs: [Compile,Test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradle
      run: |
        chmod +x gradlew
        chmod +x gradle-5.0
    - name: Assemble
      run: ./gradle-5.0/bin/gradle assemble
    - name: Upload Assember Jav
      uses: actions/upload-artifact@v2
      with:
        name: BuildJar
        path: build/libs/st_nycu_lab4_0866016-1.0-SNAPSHOT.jar
  Release:
    if: startsWith(github.event.ref, 'refs/tags/')
    needs: [Assember]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            Release.txt
            LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download math result for Assember
      uses: actions/download-artifact@v2
      with:
        name: BuildJar
        path: build/libs/st_nycu_lab4_0866016-1.0-SNAPSHOT.jar
      
