name: Java CI with Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradle
      run: |
        chmod +x gradlew
        chmod +x gradle-7.0-rc-2
    - name: Show the Gradle can work
      run: ./gradle-7.0-rc-2/bin/gradle task
    - name: Build with Gradle
      run: ./gradle-7.0-rc-2/bin/gradle compileJava
