name: Java CI with Gradle

on: [push]

jobs:
 
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: startsWith(github.ref, 'refs/tags/')
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Release.txt
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/download-artifact@v2
      with:
       name: my-artifact
       path: https://github.com/yshyang/st_nycu_lab4_0866016/releases/tag/${{ secrets.GITHUB_TOKEN }}
      
